# Generated by Django 5.1.4 on 2025-01-29 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='billing',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='prescription',
        ),
        migrations.DeleteModel(
            name='ConsultationReview',
        ),
        migrations.DeleteModel(
            name='NotificationType',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
