# Generated by Django 5.1.4 on 2025-01-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_notification_appointment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'permissions': [('can_manage_patients', 'Can manage patients'), ('can_schedule_appointments', 'Can schedule appointments'), ('can_manage_consultations', 'Can manage consultations'), ('can_manage_patient_records', 'Can manage patient records'), ('can_assist_doctors', 'Can assist doctors'), ('can_manage_inventory', 'Can manage inventory'), ('can_manage_users', 'Can manage users'), ('can_manage_website', 'Can manage website'), ('can_create_staff_accounts', 'Can create staff accounts')]},
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='last_name',
        ),
    ]
